services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/8.3/Dockerfile
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    ports:
      - '8000:80'
    environment:
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
      - './docker/8.3/php.ini:/usr/local/etc/php/php.ini'
      - './docker/8.3/000-default.conf:/etc/apache2/sites-available/000-default.conf'
      - './docker/8.3/000-default.conf:/etc/apache2/sites-enabled/000-default.conf'
    networks:
      - vegenet
networks:
  vegenet:
    driver: bridge
